name: Backup Firestore

on:
  schedule:
    - cron:  '* * * * *'

env:
  PROJECT_ID: hpe-chatbot
  BUCKET: gs://backup-hpe-chatbot
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud config set account biswajeetraut382@gmail.com
    - run: gcloud info
    - run: gcloud config set project $PROJECT_ID
    - run: gcloud firestore export $BUCKET
